### ISSUE TITLE
Input to ReLU is quantized to int8? An error in quantization_flow.png? 

### ISSUE THREAD

**Issue by chenho74** [mit-han-lab/smoothquant#11]
In [`quantization_flow.png`](https://github.com/mit-han-lab/smoothquant/blob/main/figures/quantization_flow.png) which is referenced in the int8 demo
https://github.com/mit-han-lab/smoothquant/blob/main/examples/smoothquant_opt_real_int8_demo.ipynb, input to ReLU seems to be int8 as well. Is this an error? 
As far as I know activation function's input is usually kept in floating point. 
Also in your `quantize_model` function in the other demo notebook, for fc layers, only the inputs are quantized. So input to ReLU should remain full-precision?

**Comment by Guangxuan-Xiao** [comment]
Thank you for pointing it out! We implement the ReLU function using a [ReLU epilogue](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/kernels/linear.cu#L420) in the FC1 GEMM kernels, i.e., fusing ReLU with FC1. I have checked that this operation does compute in floating point ([ElementComputeEpilogue](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/kernels/linear.cu#L400)). We will fix this error in the future revision.

However, we do not explicitly convert the input of ReLU into FP numbers. And since the epilogue of CUTLASS kernels is very efficient, the overhead of this fused kernel is roughly the same as a single GEMM.

**Comment by chenho74** [comment]
Thanks for the speedy explanation! Looking forward to the new revision.
