### ISSUE TITLE
Test smoothquant accuracy for just fc2 layer

### ISSUE THREAD

**Issue by erichan1** [mit-han-lab/smoothquant#14]
I'm integrating smoothquant into a different large autoregressive transformer model with a somewhat different arch. 

Say I want to test smoothquant accuracy just quantizing and smoothing fc2 to int8. Could you help me with the steps for this? I'm using the real PyTorch W8A8B8O8Linear layer from torch-int. 

Roughly looks like:
1. Get act scales, static decoder layer scales for whole model (or just fc2, but might be easier to do whole model). 
2. Use act scales + just the fc part of smooth_lm
3. Call the W8A8 linear kernel

I'd appreciate some help with step 3 (or just some example code for getting scales/quantizing/calling a single linear). In particular, I'm confused by what the input and output scale should be. Also looks like some of the scaling factors are fused into previous layers so not sure if that will introduce any issues. Thanks!

**Comment by erichan1** [comment]
Ok trying to break this down into simpler questions: 

1. For [fc2](https://github.com/Guangxuan-Xiao/torch-int/blob/d03a8dab0d2b725abf5dc9a28dcea85832754e38/torch_int/nn/linear.py#L219), what is input_scale? Is it the per-tensor scaling factor that you calculated on the activations in get_static_decoder_layer_scales?  
2. As a follow-up to 1, can't you calculate per-tensor activation scaling factor using the statistics you got in get_act_scales? get_act_scales gives you a vector of per-channel scaling factors which you could average to get per-tensor activation scaling. Why do you need a separate get_static_decoder_layer_scales? Not sure if I'm missing something here. 
3. Similarly, what are alpha and beta? Is alpha the final per-tensor scaling factor for the weight and beta the final per-tensor scaling factor for the input activation? 

Example code for a single matmul would be really helpful tbh - I'm still not quite understanding how the paper maps to the implementation. For the model I'm trying to use smoothquant on it's a bit difficult to copy and paste so have to re-implement some stuff.

**Comment by Guangxuan-Xiao** [comment]
Hi Eric, thank you for your interest in SmoothQuant! 

To answer your questions in short:
1. Yes, it is.
2. We convert the model into INT8 by converting each linear layers into INT8. You can check the `from_float` functions of those linear layers, e.g., [from_float](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/nn/linear.py#L219) of the [W8A8BFP32OFP32Linear](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/nn/linear.py#L182).

We use the [W8A8BFP32OFP32Linear](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/nn/linear.py#L182) to implement FC2 and `out_proj` since their outputs are the inputs of the residual adds and LayerNorms. You can check the [from_float](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/nn/linear.py#L219) function of the [W8A8BFP32OFP32Linear](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/nn/linear.py#L182) (as well as other INT8 modules) to see how we convert a FP module into an INT8 module. The `input_scale` always refers to quantization step size $\Delta$, which is the maximum absolute value in activations divided by 127 (see [get_static_decoder_layer_scales](https://github.com/mit-han-lab/smoothquant/blob/be3c4239d21be5eeba7cd425a747c0d9c08804f6/smoothquant/calibration.py#L116)).

**Comment by erichan1** [comment]
Regarding question 2, my question is where does the fp16 input get quantized into int8 first on the model? I'm looking for a call like "input.to(torch.int8)". Does it happen in the tokenizer or right at the start of OPTDecoder?

**Comment by Guangxuan-Xiao** [comment]
It happens in the [LayerNormQ](https://github.com/Guangxuan-Xiao/torch-int/blob/main/torch_int/nn/fused.py#L17).

**Comment by erichan1** [comment]
What about in the attention though? There's no layernorm before that.

**Comment by Guangxuan-Xiao** [comment]
There are LayerNorms before attention modules. Quantization always happens in LayerNormQ.

<img width="256" alt="Screenshot 2022-12-15 at 2 51 05 PM" src="https://user-images.githubusercontent.com/40906949/207953752-c2624589-5cef-498e-b53e-422c2fa57de2.png">

**Comment by erichan1** [comment]
Ok, I see. That quantizes for layers after the first one - are we not quantizing the first MHA?
