### ISSUE TITLE
Eta for PyTorch

### ISSUE THREAD

**Issue by erichan1** [mit-han-lab/smoothquant#5]
What's the eta for release in PyTorch and/or FasterTransformer? 

In PyTorch, what will the interface to use smoothquant look like? Will it be a wrapper around a linear layer or a custom linear layer?

**Comment by Guangxuan-Xiao** [comment]
Thank you for your attention! We have just released the real INT8 inference for PyTorch (https://github.com/mit-han-lab/smoothquant#smoothquant-int8-inference-for-pytorch). The FasterTransformer implementation will be released in around a week.

Since PyTorch does not support integer matrix multiplication on GPUs yet, we implement our customized INT8 Linear and BMM operators in [torch-int](https://github.com/Guangxuan-Xiao/torch-int) with CUTLASS INT8 GEMM kernels. We replace the linear layers and bmm functions in the original Huggingface model with our INT8 operators to perform real INT8 inference (see [opt.py](https://github.com/mit-han-lab/smoothquant/blob/main/smoothquant/opt.py)).

**Comment by Guangxuan-Xiao** [comment]
A preview version of our FasterTransformer implementation has been released https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md#run-meta-opt.
