### ISSUE TITLE
Latency calculation for OPT 175B

### ISSUE THREAD

**Issue by tangbinh** [mit-han-lab/smoothquant#7]
Thank you for sharing your impressive work. I have a question regarding Figure 8 in the paper where you reported latency measurements for OPT 175B with FasterTransformer FP16 and SmoothQuant. Latency appears to be less than 1ms / token (e.g. 228 ms for a sequence of 256 output tokens), but from our previous experience with FasterTransformer FP16 and 8-way tensor parallelism, latency was often around 40ms / token for a batch size of 4 sentences. The [GPT guide](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md) from the FasterTransformer repo also doesn't show any numbers near 1ms / token.

Can you please explain a bit more about the setup here? If possible, would you mind sharing your benchmark script? We also look forward to the release of SmoothQuant code as well.

**Comment by Guangxuan-Xiao** [comment]
Thank you for your interest in our work! As explained in section 5.3, we measure the _**context stage**_ latency, i.e., generating the embeddings for all tokens in _**one pass**_. This is different from the setting of [GPT guide](https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md), where it measures the _**sampling stage**_ latency, i.e., caching the embeddings of previous tokens and only compute one embedding for the next token. Since the context stage computes more embeddings at a time, the computing power of GPUs is more likely to be saturated, so the average latency per token is much lower. Nevertheless, the reported latency can also show the relative speedup brought by INT8 quantization.

A preview version of our FasterTransformer implementation has just been released https://github.com/NVIDIA/FasterTransformer/blob/main/docs/gpt_guide.md#run-meta-opt. We will also release the benchmark script soon. Please stay tuned! 😄

**Comment by Hao-YunDeng** [comment]
Hi @tangbinh and @Guangxuan-Xiao has anyone of you measured the text generation latency (per token latency) with the smoothquant models? I'm trying to experiment with model.generate() but it seems not working with smoothquant models and gives attention mask dimension error
